//
//  ClipboardManager.swift
//  SimpleNotch
//
//  Keeps the Clipboard history: watches the general pasteboard while the
//  Clipboard Tab is on, turns each copy into a Clip, persists the history and
//  writes a picked Clip back (pasting it into the previous app when allowed).
//

import AppKit
import CryptoKit
import Defaults
import ImageIO
import KeyboardShortcuts
import SwiftUI
import UniformTypeIdentifiers

@MainActor
final class ClipboardManager: ObservableObject, NotchFeature {
    static let shared = ClipboardManager()
    var enabledKey: Defaults.Key<Bool> { .tabClipboardEnabled }

    /// How many unpinned Clips the history keeps. Pinned clips don't count.
    static let historyLimit = 50

    /// Newest first. Pinned and unpinned Clips share this one list.
    @Published private(set) var clips: [Clip] = []

    var pinnedClips: [Clip] { clips.filter(\.pinned) }
    var recentClips: [Clip] { clips.filter { !$0.pinned } }

    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount = 0
    private var loaded = false
    private let ioQueue = DispatchQueue(label: "SimpleNotch.Clipboard.io", qos: .utility)
    private let thumbnails = NSCache<NSString, NSImage>()
    private var appIcons: [String: NSImage] = [:]

    /// Pasteboard types that mark content as private, transient or generated
    /// (see nspasteboard.org); such content never becomes a Clip.
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private static let maxImagePixels = 1600
    private static let maxTextLength = 1_000_000

    private init() {}

    // MARK: - Lifecycle

    func start() {
        loadIfNeeded()
        lastChangeCount = pasteboard.changeCount
        timer?.invalidate()
        let timer = Timer(timeInterval: 0.5, repeats: true) { _ in
            MainActor.assumeIsolated { ClipboardManager.shared.poll() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer

        KeyboardShortcuts.removeHandler(for: .openClipboard)
        KeyboardShortcuts.onKeyUp(for: .openClipboard) {
            MainActor.assumeIsolated {
                NotchRouter.shared.toggle(.clipboard, keyboard: true)
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        KeyboardShortcuts.removeHandler(for: .openClipboard)
    }

    // MARK: - Capture

    private var ignoreUntil = Date.distantPast

    /// Pasteboard changes in the next `seconds` are not Clips: another feature
    /// (Translate's ⌃⌥T) is borrowing the pasteboard and will restore it.
    func ignoreChanges(for seconds: TimeInterval) {
        ignoreUntil = Date.now.addingTimeInterval(seconds)
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard Date.now >= ignoreUntil else { return }
        capture()
    }

    private func capture() {
        let types = Set(pasteboard.types ?? [])
        guard !types.isEmpty, types.isDisjoint(with: Self.ignoredTypes) else { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        // Files first: Finder also puts an icon image and the names as text.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            insert(Clip(id: UUID(), kind: .file, filePaths: paths, sourceBundleID: source, date: .now,
                        pinned: false, contentKey: "f:" + paths.joined(separator: "\n")))
            return
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard string.count <= Self.maxTextLength else { return }
            if let link = Self.link(from: string) {
                insert(Clip(id: UUID(), kind: .link, text: link, sourceBundleID: source, date: .now,
                            pinned: false, contentKey: "l:" + link))
            } else {
                insert(Clip(id: UUID(), kind: .text, text: string, sourceBundleID: source, date: .now,
                            pinned: false, contentKey: "t:" + string))
            }
            return
        }

        if let url = pasteboard.string(forType: .URL), let link = Self.link(from: url) {
            insert(Clip(id: UUID(), kind: .link, text: link, sourceBundleID: source, date: .now,
                        pinned: false, contentKey: "l:" + link))
            return
        }

        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
            captureImage(data, source: source)
        }
    }

    /// A single-line string that is a web or mail link.
    private static func link(from string: String) -> String? {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.contains(where: \.isWhitespace),
              let url = URL(string: trimmed),
              let scheme = url.scheme?.lowercased(),
              ["http", "https", "mailto", "ftp"].contains(scheme),
              scheme == "mailto" || url.host != nil
        else { return nil }
        return trimmed
    }

    private func captureImage(_ data: Data, source: String?) {
        let directory = imagesDirectory
        let maxPixels = Self.maxImagePixels
        Task.detached(priority: .utility) {
            let hash = SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            let key = "i:" + hash
            let existing = await MainActor.run { ClipboardManager.shared.clips.first { $0.contentKey == key } }
            if let existing {
                await ClipboardManager.shared.bump(existing.id, source: source)
                return
            }
            guard let (png, size) = Self.downscaledPNG(data, maxPixels: maxPixels) else { return }
            let id = UUID()
            let fileName = id.uuidString + ".png"
            do {
                try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
                try png.write(to: directory.appendingPathComponent(fileName), options: .atomic)
            } catch {
                return
            }
            let clip = Clip(id: id, kind: .image, imageFileName: fileName, imagePixelSize: size,
                            sourceBundleID: source, date: .now, pinned: false, contentKey: key)
            await ClipboardManager.shared.insert(clip)
        }
    }

    nonisolated private static func downscaledPNG(_ data: Data, maxPixels: Int) -> (Data, CGSize)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixels,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(output, UTType.png.identifier as CFString, 1, nil) else {
            return nil
        }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination) else { return nil }
        return (output as Data, CGSize(width: image.width, height: image.height))
    }

    /// Adds a Clip at the top, or moves the existing Clip with the same content there.
    private func insert(_ clip: Clip) {
        if let existing = clips.first(where: { $0.contentKey == clip.contentKey }) {
            if clip.kind == .image, clip.imageFileName != existing.imageFileName {
                removeImageFile(of: clip)
            }
            bump(existing.id, source: clip.sourceBundleID)
            return
        }
        withMotion(Motion.snappy) {
            clips.insert(clip, at: 0)
            trim()
        }
        save()
    }

    /// Moves a Clip to the top of its section, marking it as just copied.
    private func bump(_ id: UUID, source: String? = nil) {
        guard let index = clips.firstIndex(where: { $0.id == id }) else { return }
        withMotion(Motion.snappy) {
            var clip = clips.remove(at: index)
            clip.date = .now
            if let source { clip.sourceBundleID = source }
            clips.insert(clip, at: 0)
        }
        save()
    }

    private func trim() {
        var unpinnedSeen = 0
        var dropped: [Clip] = []
        clips.removeAll { clip in
            guard !clip.pinned else { return false }
            unpinnedSeen += 1
            if unpinnedSeen > Self.historyLimit {
                dropped.append(clip)
                return true
            }
            return false
        }
        dropped.forEach(removeImageFile)
    }

    // MARK: - Editing

    func togglePin(_ clip: Clip) {
        guard let index = clips.firstIndex(where: { $0.id == clip.id }) else { return }
        withMotion(Motion.snappy) {
            clips[index].pinned.toggle()
            trim()
        }
        save()
    }

    func delete(_ clip: Clip) {
        withMotion(Motion.snappy) {
            clips.removeAll { $0.id == clip.id }
        }
        removeImageFile(of: clip)
        save()
    }

    /// Removes every unpinned Clip; Pinned clips stay.
    func clearHistory() {
        loadIfNeeded()
        let removed = recentClips
        withMotion(Motion.snappy) {
            clips.removeAll { !$0.pinned }
        }
        removed.forEach(removeImageFile)
        save()
    }

    // MARK: - Picking

    /// Writes the Clip back to the pasteboard and moves it to the top.
    /// The write is marked so the monitor doesn't capture it again.
    @discardableResult
    func copyToPasteboard(_ clip: Clip) -> Bool {
        pasteboard.clearContents()
        var written = false
        switch clip.kind {
        case .text:
            written = pasteboard.setString(clip.text ?? "", forType: .string)
        case .link:
            let link = clip.text ?? ""
            pasteboard.declareTypes([.URL, .string], owner: nil)
            pasteboard.setString(link, forType: .URL)
            written = pasteboard.setString(link, forType: .string)
        case .image:
            if let url = imageURL(of: clip), let data = try? Data(contentsOf: url) {
                pasteboard.declareTypes([.png, .tiff], owner: nil)
                written = pasteboard.setData(data, forType: .png)
                if let tiff = NSImage(data: data)?.tiffRepresentation {
                    pasteboard.setData(tiff, forType: .tiff)
                }
            }
        case .file:
            let urls = clip.fileURLs.filter { FileManager.default.fileExists(atPath: $0.path) }
            written = !urls.isEmpty && pasteboard.writeObjects(urls as [NSURL])
        }
        lastChangeCount = pasteboard.changeCount
        if written { bump(clip.id) }
        return written
    }

    /// Posts a synthetic ⌘V to whichever app is frontmost.
    func postPaste() {
        let source = CGEventSource(stateID: .combinedSessionState)
        let keyV: CGKeyCode = 9
        let down = CGEvent(keyboardEventSource: source, virtualKey: keyV, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: keyV, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    // MARK: - Images and icons

    func imageURL(of clip: Clip) -> URL? {
        clip.imageFileName.map { imagesDirectory.appendingPathComponent($0) }
    }

    func cachedThumbnail(for clip: Clip) -> NSImage? {
        thumbnails.object(forKey: clip.id.uuidString as NSString)
    }

    /// A small thumbnail of an image Clip, decoded off the main thread.
    func thumbnail(for clip: Clip) async -> NSImage? {
        if let cached = cachedThumbnail(for: clip) { return cached }
        guard let url = imageURL(of: clip) else { return nil }
        let image = await Task.detached(priority: .userInitiated) { () -> NSImage? in
            guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else { return nil }
            let options: [CFString: Any] = [
                kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceCreateThumbnailWithTransform: true,
                kCGImageSourceThumbnailMaxPixelSize: 96,
            ]
            guard let cg = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
            return NSImage(cgImage: cg, size: NSSize(width: cg.width / 2, height: cg.height / 2))
        }.value
        if let image { thumbnails.setObject(image, forKey: clip.id.uuidString as NSString) }
        return image
    }

    func appIcon(for bundleID: String?) -> NSImage? {
        guard let bundleID else { return nil }
        if let icon = appIcons[bundleID] { return icon }
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) else { return nil }
        let icon = NSWorkspace.shared.icon(forFile: url.path)
        appIcons[bundleID] = icon
        return icon
    }

    func fileIcon(for clip: Clip) -> NSImage? {
        guard let first = clip.filePaths?.first else { return nil }
        return NSWorkspace.shared.icon(forFile: first)
    }

    private func removeImageFile(of clip: Clip) {
        guard let url = imageURL(of: clip) else { return }
        thumbnails.removeObject(forKey: clip.id.uuidString as NSString)
        ioQueue.async { try? FileManager.default.removeItem(at: url) }
    }

    // MARK: - Persistence

    private var directory: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("SimpleNotch/Clipboard", isDirectory: true)
    }

    private var imagesDirectory: URL { directory.appendingPathComponent("Images", isDirectory: true) }
    private var historyURL: URL { directory.appendingPathComponent("history.json") }

    func loadIfNeeded() {
        guard !loaded else { return }
        loaded = true
        guard let data = try? Data(contentsOf: historyURL) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        clips = (try? decoder.decode([Clip].self, from: data)) ?? []
    }

    private func save() {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        guard let data = try? encoder.encode(clips) else { return }
        let directory = directory
        let url = historyURL
        ioQueue.async {
            try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            try? data.write(to: url, options: .atomic)
        }
    }
}
